### ISSUE TITLE
Timeouts from guessing for Users

### ISSUE THREAD

**Issue by Wissididom** [GeorgeCiesinski/poke-guesser-bot#38]
Simply a Admin Command to put a player in an timeout. I thought of these commands:

- `!timeout <@user> daily <unix-timestamp-of-the-first-timeout> [<unix-timestamp-when-the-timeouts-stop>]`
- `!timeout <@user> time 1h0m0s`
- `!timeout <@user> time <start-unix-timestamp> <end-unix-timestamp>`
- `!timeout <@user> guesses <amount>`
- `!timeout <@user> infinite`

For removing the timeout i thought of: `!untimeout <@user>`

**Comment by GeorgeCiesinski** [comment]
Regarding this change, can we workshop this a bit? I am concerned that a timeout on its own might not be user friendly, and may serve as a punishment to users rather than achieving the goal of slowing them down. What do you think of doing something like:

`!delay <@user> 15` - Rejects that user's guesses for 15 minutes after `!explore` is ran to allow other users to guess
`!delay <@user> 0` - Returns user to normal delay of 0 minutes

This is just a thought, but the benefit of this would be that rather than timing out a user and preventing them from playing, it still lets them play while mandating a delay to allow other players the chance to guess first.

**Comment by Wissididom** [comment]
We could do that but i think we also could add the feature to give hours, minutes, seconds if wanted so something like making the following both possible:
`!delay <@user> <minutes>` and `!delay [<hours>h][<minutes>m][<seconds>s]` where `[` and `[` are making it optional, but sending an error to the channel when only `!delay` is given which should also be done if we won't do that enhancement i just discribed.
