### ISSUE TITLE
Migration command

### ISSUE THREAD

**Issue by Wissididom** [GeorgeCiesinski/poke-guesser-bot#79]
# Describe the new feature
A simple discord command for migrating the replit database to the new postgres database by providing the value of the REPLIT_DB_URL env var from replit.

## Describe alternatives you've considered
Another option would be to simply get all settings and such and resetup them in the new version, but that has a higher expense depending on how much users might need to do that.

## Planning
I thought of some command like `/migrate <replit_db_url>` which can be enabled in the .env for migrating the old replit database to postgres. We can probably even write the command to get it (`echo $REPLIT_DB_URL`) in the description of the command.

### API
Simply like with every other command to give them their own file and just call their main function (in this case probably `migrate` in the file `migrate.js`)

## Useful links

1. [Replit Database FAQ](https://docs.replit.com/hosting/database-faq)
2. [Using Databases in Replit](https://docs.replit.com/hosting/using-a-database)
3. [Replit's Database Module on NPM](https://www.npmjs.com/package/@replit/database)

**Comment by GeorgeCiesinski** [comment]
I was just going through the issues and wanted to see if we need to keep this one open. As far as I know, there is one user who is officially using the replit version. If that is the case, it might not make sense to write a feature that is only going to be used once. 

Assuming this user is going to switch to the new version once it is released, is data going to need to be transferred, or can it be done following a "championship" so that a new game can start from scratch in the new version? 

Also, is there any changes that need to happen on the discord bot settings? I know that the slash commands need to be installed, but besides that, is there anything else that needs done?

**Comment by Wissididom** [comment]
If that guy ends it with a championship it would be resetting up the allowed mods and allowed channels although the guy could also simply set it within Discords Command Permission system. Other than that I think running setupCommands once and running the bot would be enough.

If he/she does not want to reset the scores he'd need to use the `/mod score` subcommands for each user.

As I don't think people using the replit bot have a lot of members in their server I'm fine with not creating the migration command for the reason you mentioned.

Also the guy at some point has to move over to the new version because discord.js v12 won't be supported by Discord (for the API version they talk to) forever.

**Comment by GeorgeCiesinski** [comment]
Got it. In that case I will go ahead and close this issue.
